name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myapp .

    # - name: Run tests
    #   run: docker run myapp npm test

    - name: Push Docker image to registry
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag myapp ${{ secrets.DOCKER_REGISTRY }}/myapp
        docker push ${{ secrets.DOCKER_REGISTRY }}/myapp
